GET https://signin-server.herokuapp.com/users

###

POST https://signin-server.herokuapp.com/users
Content-Type: application/json

{
  "name": "Paweł",
  "surname": "Bąk",
  "login": "pbak",
  "password": "test"
}

###

POST https://signin-server.herokuapp.com/users/login
Content-Type: application/json

{
  "name": "Paweł",
  "surname": "Bąk",
  "login": "pbak",
  "password": "test"
}